# Generated by Django 4.0.3 on 2022-11-30 18:27

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_subcart_cart'),
        ('paymentsApp', '0002_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dukaan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='mainApp.dukaan'),
        ),
    ]
