# Generated by Django 4.0.3 on 2022-11-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsApp', '0004_remove_order_dukaan_order_dukaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dukaan',
        ),
    ]
