# Generated by Django 4.0.3 on 2022-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukanAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_cart',
            field=models.BooleanField(default=False),
        ),
    ]
