# Generated by Django 4.0.3 on 2022-11-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dukaan',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
