# Generated by Django 4.0.3 on 2022-12-02 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0004_subcart_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('pan_no', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('dukaan', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='mainApp.dukaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
