# Generated by Django 4.0.3 on 2022-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_withdrawlform'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawlform',
            name='status',
            field=models.TextField(default='PENDING'),
        ),
    ]
