# Generated by Django 4.0.3 on 2022-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_withdrawlform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawlform',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
